### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by leebaird** [swright573/site-map-extractor#1]
1. Extract Response Coded: enable 500 by default.
2. Log: sort by columns, especially Response Code.

**Comment by dVb-william** [comment]
Hi,

Both issues fixed in https://github.com/dVb-william/site-map-extractor. Could you re-test?

**Comment by swright573** [comment]
I tested both issues and your fixes worked perfectly.

**Comment by swright573** [comment]
I tested both issues you fixed and everything work perfectly. Thanks! I presume you'll create a pull request in swright573? (I'm not a GitHub whiz ... I mainly fumble around figuring out what I need to do.)


On December 17, 2019 at 2:51 PM, dVb-william <notifications@github.com> wrote:



Hi,

Both issues fixed in https://github.com/dVb-william/site-map-extractor. Could you re-test?

**Comment by swright573** [comment]
https://code.visualstudio.com/docs/containers/ssh
